color_list1=set(["blue","red","green"])
color_list2=set(["red","pink"])
print("The original set of elements are:")
print(color_list1)
print(color_list2)
print("Difference of color_list1 and color_list2")
print(color_list1.difference(color_list2))
print("Difference of color_list2 and color_list1")
print(color_list2.difference(color_list1))
